In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='qname')

In [15]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [16]:
df.head()

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [21]:
high_salary = (df['ConvertedCompYearly'] > 70000)

In [23]:
df.loc[high_salary, ['Country', 'LanguageHaveWorkedWith', 'ConvertedCompYearly']]

,Country,LanguageHaveWorkedWith,ConvertedCompYearly
ResponseId,,,
13,Germany,C;C++;Java;Perl;Ruby,77290.0
19,Singapore,C++;Python,160932.0
25,Germany,C++;HTML/CSS;Java;JavaScript;Kotlin;Node.js;Ty...,77831.0
27,Switzerland,C++;Python,81319.0
32,Israel,Bash/Shell;Go;Java;Node.js;Python;Scala;SQL,122580.0
...,...,...,...
83431,United States of America,APL;Clojure;LISP;Python;Ruby;SQL;TypeScript,125000.0
83433,Canada,Ruby,80169.0
83435,United States of America,Clojure;Kotlin;SQL,160500.0
83437,United States of America,Groovy;Java;Python,90000.0
83438,Canada,Bash/Shell;JavaScript;Node.js;Python,816816.0

In [24]:
countries = ['United States of America', 'India', 'China', 'Canada', 'Germany', 'United Kingdom']

In [25]:
filt = df['Country'].isin(countries)

In [28]:
df.loc[filt, 'Country']

ResponseId
6        United States of America
7        United States of America
9                           India
13                        Germany
16       United States of America
                   ...
83431    United States of America
83433                      Canada
83435    United States of America
83437    United States of America
83438                      Canada
Name: Country, Length: 35491, dtype: object

In [29]:
df['LanguageHaveWorkedWith']

ResponseId
1        C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift
2                                    JavaScript;Python
3                             Assembly;C;Python;R;Rust
4                                JavaScript;TypeScript
5                       Bash/Shell;HTML/CSS;Python;SQL
                             ...
83435                               Clojure;Kotlin;SQL
83436                                              NaN
83437                               Groovy;Java;Python
83438             Bash/Shell;JavaScript;Node.js;Python
83439           Delphi;Elixir;HTML/CSS;Java;JavaScript
Name: LanguageHaveWorkedWith, Length: 83439, dtype: object

In [30]:
filt = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)
df.loc[filt, 'LanguageHaveWorkedWith']

ResponseId
2                                        JavaScript;Python
3                                 Assembly;C;Python;R;Rust
5                           Bash/Shell;HTML/CSS;Python;SQL
6        C;C#;C++;HTML/CSS;Java;JavaScript;Node.js;Powe...
10                                              C++;Python
                               ...
83430               HTML/CSS;PHP;PowerShell;Python;SQL;VBA
83431          APL;Clojure;LISP;Python;Ruby;SQL;TypeScript
83432    C#;Dart;HTML/CSS;Java;JavaScript;Kotlin;Node.j...
83437                                   Groovy;Java;Python
83438                 Bash/Shell;JavaScript;Node.js;Python
Name: LanguageHaveWorkedWith, Length: 39792, dtype: object